# Generated by Django 5.0.6 on 2024-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='mobile_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
